<a href="https://colab.research.google.com/github/PabloDuranL/Aplicaciones/blob/main/Pandapractica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [140]:
data=pd.Series([3,5,2,6])
data,data.values,data.index

(0    3
 1    5
 2    2
 3    6
 dtype: int64,
 array([3, 5, 2, 6]),
 RangeIndex(start=0, stop=4, step=1))

In [141]:
data[1],data[1:3], data[:-1]

(np.int64(5),
 1    5
 2    2
 dtype: int64,
 0    3
 1    5
 2    2
 dtype: int64)

In [142]:
data=pd.Series([3,5,2,6], index=['messi','ronaldo','ilya','lasha'])
data['messi'],data

(np.int64(3),
 messi      3
 ronaldo    5
 ilya       2
 lasha      6
 dtype: int64)

In [143]:
xd={'messi':5,'ilya':56,'lasha':45}
data=pd.Series(xd)
data, data['messi']

(messi     5
 ilya     56
 lasha    45
 dtype: int64,
 np.int64(5))

In [144]:
data['messi':'ilya']

,0
messi,5
ilya,56


In [145]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1,2,3])

,0
1,b
2,a
3,c


In [146]:
snatch_dict={'ilya':198,'lasha':225,'nassar':188,'pablo':105}
cleanandjerk_dict={'ilya':262,'lasha':267,'nassar':228,'pablo':120}

snatch=pd.Series(snatch_dict)
cleanandjerk=pd.Series(cleanandjerk_dict)
marcas=pd.DataFrame({'mejor snatch':snatch_dict, 'mejor envion':cleanandjerk_dict})
marcas, marcas.index, marcas.columns

(        mejor snatch  mejor envion
 ilya             198           262
 lasha            225           267
 nassar           188           228
 pablo            105           120,
 Index(['ilya', 'lasha', 'nassar', 'pablo'], dtype='object'),
 Index(['mejor snatch', 'mejor envion'], dtype='object'))

In [147]:
marcas['mejor snatch']

,mejor snatch
ilya,198
lasha,225
nassar,188
pablo,105


In [148]:
pd.DataFrame(snatch,columns=['mejor snatch'])

,mejor snatch
ilya,198
lasha,225
nassar,188
pablo,105


In [149]:
data = [{'a': i, 'b': 2 * i}
        for i in range(6)]
pd.DataFrame(data)

,a,b
0,0,0
1,1,2
2,2,4
3,3,6
4,4,8
5,5,10


In [150]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}], index=[9,3])

,a,b,c
9,1.0,2,NaN
3,NaN,3,4.0


In [151]:
x=np.random.randint(100,200, size=(4,3))
x

array([[180, 189, 158],
       [196, 192, 168],
       [188, 124, 178],
       [106, 180, 139]])

In [152]:
resultados=pd.DataFrame(x,columns=['arr','env','sent'], index=['pablo','lasha','ilya','klokov'])

In [153]:
resultados['total']= resultados['arr']+resultados['env']
resultados

,arr,env,sent,total
pablo,180,189,158,369
lasha,196,192,168,388
ilya,188,124,178,312
klokov,106,180,139,286


In [154]:
resultados.loc['ilya']

,ilya
arr,188
env,124
sent,178
total,312


In [155]:
resultados - resultados.loc['ilya']


,arr,env,sent,total
pablo,-8,65,-20,57
lasha,8,68,-10,76
ilya,0,0,0,0
klokov,-82,56,-39,-26


In [156]:
ind = pd.Index([2,3])
ind


Index([2, 3], dtype='int64')

In [157]:
edad_d={'sally':2,'pucca':6}
peso_d={'sally':7, 'pucca':15}
edad=pd.Series(edad_d)
peso=pd.Series(peso_d)
pd.DataFrame({'edad':edad_d,'peso':peso_d})


,edad,peso
sally,2,7
pucca,6,15


In [158]:
resultados.iloc[0:2]

,arr,env,sent,total
pablo,180,189,158,369
lasha,196,192,168,388


In [159]:
resultados.iloc[0]

,pablo
arr,180
env,189
sent,158
total,369


In [160]:
resultados.loc[resultados.arr>150,'env']

,env
pablo,189
lasha,192
ilya,124


In [161]:
resultados.loc[resultados.arr>150,['total','sent']]

,total,sent
pablo,369,158
lasha,388,168
ilya,312,178


In [162]:
resultados.iloc[0,3]=200
resultados

,arr,env,sent,total
pablo,180,189,158,200
lasha,196,192,168,388
ilya,188,124,178,312
klokov,106,180,139,286


In [163]:
resultados.loc[::2,['total','sent']]=[200,209]
resultados

,arr,env,sent,total
pablo,180,189,209,200
lasha,196,192,168,388
ilya,188,124,209,200
klokov,106,180,139,286


In [164]:
df = pd.DataFrame(np.random.randint(0, 10, size=(3, 4)),
                  columns=list('ABCD'))
df

,A,B,C,D
0,6,3,5,5
1,9,5,7,5
2,8,5,8,0


In [165]:
rng=np.random.RandomState(4)
rng.randint(150,200)

196

In [166]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

df.dropna(axis='columns')

,2
0,2
1,5
2,6


In [167]:
x=np.random.rand(3,3)
y=np.random.rand(3)
np.hstack((x, y[:, np.newaxis]))
np.vstack((x,y)), y[:,np.newaxis].shape

(array([[0.15268427, 0.88152486, 0.30546318],
        [0.2794066 , 0.80693323, 0.68288056],
        [0.35268135, 0.8988825 , 0.99491749],
        [0.73615651, 0.54144185, 0.22026012]]),
 (3, 1))

In [168]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

,0
a,1.0
b,NaN
c,2.0
d,NaN
e,3.0


In [169]:
data.fillna(6)

,0
a,1.0
b,6.0
c,2.0
d,6.0
e,3.0


In [170]:
data.fillna(method='ffill')

/tmp/ipykernel_11355/1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


,0
a,1.0
b,1.0
c,2.0
d,2.0
e,3.0


In [171]:
data.fillna(method='bfill')

/tmp/ipykernel_11355/1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


,0
a,1.0
b,2.0
c,2.0
d,3.0
e,3.0


In [172]:
df

,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,NaN,4.0,6


In [173]:
df.fillna(method='ffill', axis=0)

/tmp/ipykernel_11355/3122255136.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=0)


,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,2.0,4.0,6


In [174]:
df.dropna()

,0,1,2
1,2.0,3.0,5


In [175]:
index=[('ilya',2008),('ilya',2012)]
snatch=np.array([345,367])
envion=np.array([343,345])
marcas=[snatch,envion]
df = pd.DataFrame(marcas, index=index) # Create DataFrame with default column names
df.columns = ['Mejor total','Mejor envion'] # Assign desired column names
df

,Mejor total,Mejor envion
"(ilya, 2008)",345,367
"(ilya, 2012)",343,345


In [176]:
index = pd.MultiIndex.from_tuples(index)
index
df.reindex(index)

Mejor total  Mejor envion
ilya 2008          345           367
     2012          343           345

In [177]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

,0
"(California, 2000)",33871648
"(California, 2010)",37253956
"(New York, 2000)",18976457
"(New York, 2010)",19378102
"(Texas, 2000)",20851820
"(Texas, 2010)",25145561


In [178]:
pop[('California',2000):('New York',2010)]

,0
"(California, 2000)",33871648
"(California, 2010)",37253956
"(New York, 2000)",18976457
"(New York, 2010)",19378102


In [179]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [180]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [181]:
pop[:, 2010]

,0
California,37253956
New York,19378102
Texas,25145561


In [182]:
pop_df=pop.unstack()
pop_df

,2000,2010
California,33871648,37253956
New York,18976457,19378102
Texas,20851820,25145561


In [183]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [184]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [185]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [186]:
f_u18.unstack()

,2000,2010
California,0.273594,0.249211
New York,0.247010,0.222831
Texas,0.283251,0.273568


In [191]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.193403  0.699347
  2  0.777918  0.435475
b 1  0.605903  0.960217
  2  0.238377  0.105228

In [ ]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)